platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!


target 'InstagramMe' do

#SOCIAL
pod 'InstagramKit', '~> 3.0'
pod 'UICKeyChainStore'

#UI
pod 'Masonry'
pod 'YYWebImage'
pod 'AsyncDisplayKit', '~> 1.9.8'
pod 'TLYShyNavBar', '~> 1.1'
pod 'ResponsiveLabel', '~> 1.0.11'
pod 'STTweetLabel'

#ANIMATIONS
pod 'pop', :git => 'https://github.com/facebook/pop.git'

end

