# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/anodamobi/ANODA-CocoaPods.git'

inhibit_all_warnings!


target 'InstagramMe' do

#SOCIAL
pod 'InstagramKit', '~> 3.0'

#ANODA
pod 'ANHelperFunctions'
pod 'ANLogger'

#UI
pod 'Masonry'
pod 'YYWebImage'

end

